# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50)),
                ('workcity', models.CharField(max_length=30)),
                ('education_background', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=30)),
                ('job_form', models.CharField(max_length=30)),
                ('company_form', models.CharField(max_length=30)),
                ('kill', models.CharField(max_length=50)),
            ],
        ),
    ]
